### ISSUE TITLE
Images are not rescaled in backend

### ISSUE THREAD

**Issue by vigri** [YAG-Gallery/yag#45]
Hello,

I've made a fresh installation of Typo3 6.2.0 LTS and YAG 4.0.6

After setting up the sys-folder and adding some images to an example album there seems to be a bug:

![yag_bug](https://cloud.githubusercontent.com/assets/2580723/10124254/155b4b24-6551-11e5-98d1-63678e69e82a.png)

As you can see the images are shown in their original size - not resized

Could this be a bug or a missing setting in my typo install?
The screenshot is taken from Firefox, but same thing can be reproduced on Chrome.

**Comment by daniellienert** [comment]
Hey, have you installed YAG via TER or git?

**Comment by elijahalcantara** [comment]
Hi, I can confirm this issue in typo3 v7 as well. I'm using yag 4.0.7 , under windows xampp , php 5.6

**Comment by royledermueller** [comment]
Same here.
Bilder werden weder im Backend, noch im Frontend reduziert.
Die Thumbs werden erzeugt, haben aber die gleiche Größe.
Typo3 7.6.2. Im Backend und Frontend werden keine Fehler geworfen und alle Angeforderten Bilder wurden gefunden. Ich bin allerdings noch kein Profi mit Typo3. Bin daher für Hilfe beim Debuggen dankbar.

**Comment by pdieter** [comment]
I have a problem which may be related. I moved a TYPO3 installation to a development environment and viewed some images in the album, which were not resized (like in the image above).

I fixed the missing dependencies like imagemagick and now the resizing works fine for the image i have not been already watching. I am not able to tell the system to regenerate those images. I cleared the resoluion cache, cleared the temp folder, regeneraded the resolution, cleared all caches in the install tool. But on viewing the album the images are just regeneradet without resizing.

I am not able to find a place where those resolutions get saved to clear them.

I am running typo3 7.6.6 with yag 4.1.1 from the ter.

**Comment by pdieter** [comment]
Ok, after taking a break and thinking about the whole thing again i found a solution for my problem:

I trunkated the table cf_cache_imagesizes and voila, the images are perfectly resized.

**Comment by arnekolja** [comment]
Still a problem with 4.1.1 and 7.6.9. Truncating cf_cache_imagesizes did not help.

Seems to happen only when importing from filesystem (user_upload). When importing via drag and drop it seems to work.

**Comment by pdieter** [comment]
Wich OS and PHP version?

To ask for the obvious: The image processing tests in the setup tool are passing?

**Comment by arnekolja** [comment]
* YAG 4.1.1
* TYPO3 CMS 7.6.9
* ImageMagick 6.7.7-10
* PHP 5.6.17
* Linux (4.1.18)
* Test "Convert image formats to jpg": pass
* Test "Writing gif and png": pass
* Test "Scaling images": pass
* Test "GDLib": pass
* Test "Combining images": pass

**Comment by hocomadvies** [comment]
Hi, I am experiencing the same problem as @vigri mentioned. 
I have YAG plugin running on Typo3 7.6.15 and installed from Ter. 
My php version is php 7   with ImageMagick 6.8.9-9

In the FE all looks good. But in the BE it is not. For the end user this is not working. Images are much much to big! 
How to solve this? Any ideas? 

Thanks W.

**Comment by hocomadvies** [comment]
Any progress on this? Please advise need to solve this.

**Comment by netthinks** [comment]
Same problem here, TYPO3 7.6.15 with YAG 4.2.1 from TER, PHP 5.6

**Comment by Moongazer** [comment]
Also in TYPO3 7.6.18 with YAG 4.2.1 from TER, PHP 7.0, ImageMagick 7.0.5-x64, Apache 2.4, Windows 8.1

```
Core: Error handler (BE): PHP Warning: Declaration of Tx_Yag_ViewHelpers_Uri_GalleryViewHelper::render($galleryUid = NULL, Tx_Yag_Domain_Model_Gallery $gallery = NULL, $pageUid = NULL, $pageType = 0, $noCache = false, $noCacheHash = false, $section = '', $format = '') should be compatible with Tx_PtExtlist_ViewHelpers_Uri_ActionViewHelper::render($action = NULL, array $arguments = Array, $controller = NULL, $extensionName = NULL, $pluginName = NULL, $pageUid = NULL, $pageType = 0, $noCache = false, $noCacheHash = false, $section = '', $format = '', $linkAccessRestrictedPages = false, array $additionalParams = Array, $absolute = false, $addQueryString = false, array $argumentsToBeExcludedFromQueryString = Array) in D:\Workspace\htdocs\customers\xyz\typo3conf\ext\yag\Classes\ViewHelpers\Uri\GalleryViewHelper.php line 34
``` 
and

`Core: Error handler (BE): PHP Warning: Declaration of Tx_Yag_ViewHelpers_Link_GalleryViewHelper::render([...]) in D:\Workspace\htdocs\customers\xyz\typo3conf\ext\yag\Classes\ViewHelpers\Link\GalleryViewHelper.php line 32`

**Comment by SevenbitsIt** [comment]
Same Problem Typo3 7.6.23 YAG 4.2.1 from TER, Php 5.6. Images not resized in BE nor in FE. Is anyone reading this?
